### ISSUE TITLE
[Java] [Products API] Development Issue

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/ecommerce#5]
Start to code the Products API. This Issue will be updated with the progress and what will be done.

- [x] Create Grails Environment
- [x] Add Dependencies (Gradle)
- [x] Start Writing Packages
- [x] Create the Models
- [x] Create the Paths
- [x] Create Business Logic and Validations
- [x] Test Functionality Locally
- [x] Create Unit Tests
- [x] Observe Builds and Coverage Reports Result.

**Comment by ovflowd** [comment]
**Updated**
- Coded Stock Domain Model
- Coded Products Domain Model

**Comment by ovflowd** [comment]
**Updated**
- Finished Models
- Finished API Controllers

**To-do**
- Code Unit Tests
- Check if all validations are right.

**Comment by ovflowd** [comment]
**Updated**
- Improvements in Business Logic to prevent BL leaks
- Cleaned Code and Improved Documentation
- Started Writing System and Unit test Cases

**To-Do**
- Finish Test Cases
- Test behavior on build systems and check coverage report.

**Comment by ovflowd** [comment]
**Updated**
- Builds working correctly, updating Coverage to work as expected.

**To-Do**
- Code Unit Tests

**Comment by ovflowd** [comment]
**Updated**
- Finished Unite Tests
- Improved Domains Constraints Validation
- Added JaCoCo and Cobertura for Code Coverage

**Final Steps**
- Do Security with JWT (Update the Swagger Documentation for it too)
- Test the API with Security

**Comment by ovflowd** [comment]
**Observation**
- Will first code Purchases API, after that. Will code the Security of both.

**Comment by ovflowd** [comment]
**Question 1**
- Thinking how the Token will fit on this API scenario. So in this scenario, Tokens will not be generated on this API, only decoded.
- The purpose of the Token on this API it's create a semantic context for who it's interacting with the API. So Tokens will not be **obrigatory**. But if you provide a Token, will be Added an Operation Log that someone did something.
- The best fit scenario (and only one) it's when you Add a new Stock Entry (can be positive or negative). So if an User it's doing Checkout on his Purchases, the Token will be provided and will be decoded and stored who did the changes on the Stock entries.
- The content of the JWT token comes from the Purchase API, and will be in synthesis:

```json
{"customer": "Marcelo Parise", "email": "marcelo.parise@pismo.io", "expiresOn": "08/06/2017 00:00"}
```
- Also will be validated the date of expirancy.
- In synthesis we will have a new Domain Class on our Database Schema (ProductsAPI/PurchaseAPI)
  - OperationsLog
- This table will be both used for register log of new Products being added/removed and stock entries.
- This Domain will be also added on the PurchaseAPI

**Comment by ovflowd** [comment]
**Updated**
- Finished OperationsLog
- Finished everything

**All done, Closing**
