### ISSUE TITLE
[Java] [Purchase API] Development Issue

### ISSUE THREAD

**Issue by ovflowd** [sant0ro/ecommerce#9]
Start to code the Purchase API. This Issue will be updated with the progress and what will be done.

- [x] Create Grails Environment
- [x] Add Dependencies (Gradle)
- [x] Start Writing Packages
- [x] Create the Models
- [x] Create the Paths
- [x] Create Business Logic and Validations
- [x] Test Functionality Locally
- [x] Create Unit Tests
- [x] Observe Builds and Coverage Reports Result.

**Comment by ovflowd** [comment]
**Question 1**
- With the Purchase API it's interesting put a `expire session` on the JWT token? Since carts can expire. But if a cart expire, does it need to be removed from the Database?
- Should we don't care if a cart expire or not?
- Maybe I add this on the end as an extra.

**Comment by ovflowd** [comment]
**Answer 1** (Related to Question 1)
- Okay, thinking about it it's a good idea the PurchaseAPI token expire. In the case of Purchase API tokens will be used to Add or Remove Items from the Basket. If the Token expired the User will not be able anymore to Add/Remove Item or do Checkout. But he can remove the Cart if he want.
- For Creating Carts or Listing Carts will not be asked a Token, since the intend of the Token usage on this API it's to assegure that only the owner of the Basket will do modifications on his Cart.

**Comment by ovflowd** [comment]
**Answer 2** (Related to Question 1)
- Thinking how the Token will fit on this API scenario. So in this scenario, Tokens will not be generated on this API, only decoded.
- The purpose of the Token on this API it's create a semantic context for who it's interacting with the API. So Tokens will not be **obrigatory**. But if you provide a Token, will be Added an Operation Log that someone did something.
- The best fit scenario (and only one) it's when you Add a new Stock Entry (can be positive or negative). So if an User it's doing Checkout on his Purchases, the Token will be provided and will be decoded and stored who did the changes on the Stock entries.
- The content of the JWT token comes from the Purchase API, and will be in synthesis:

```json
{"customer": "Marcelo Parise", "email": "marcelo.parise@pismo.io", "expiresOn": "08/06/2017 00:00"}
```
- Also will be validated the date of expirancy.
- In synthesis we will have a new Domain Class on our Database Schema (ProductsAPI/PurchaseAPI)
  - OperationsLog
- This table will be both used for register log of new Products being added/removed and stock entries.
- This Domain will be also added on the PurchaseAPI

**Comment by ovflowd** [comment]
**Updated**
- Pre-finished Models
- Writing the CartController

**To-do**
- Test if the Application Works
- Code connection with the Products API
- Implement Unit & Integration Tests

**Comment by ovflowd** [comment]
**Updated**
- Finished PurchaseAPI

**To-do**
- Implement Unit & Integration Tests

**Comment by ovflowd** [comment]
**Updated**
- Finished Unit & Integration Tests
- Finished Security.

**All done, Closing**
